<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Kit\Reactive\TypeScript\ReactiveMapGenerator;
use Spatie\TypeScriptTransformer\TypeScriptTransformer;
use Spatie\TypeScriptTransformer\TypeScriptTransformerConfig;

/**
 * Writes resources/js/types/generated.d.ts: every #[TypeScript] Data class
 * as a global `App.*` type, the `Kit.ReactiveMap` for the typed reactive
 * composables, and the `window.__APP_CONFIG__` declaration. `--check`
 * fails when the committed file differs, so CI catches a stale one.
 */
class TypesGenerateCommand extends Command
{
    protected $signature = 'types:generate {--check : Fail when the committed file is out of date instead of writing}';

    protected $description = 'Regenerate resources/js/types/generated.d.ts from the PHP data classes and reactive registry';

    public function handle(Filesystem $files, TypeScriptTransformerConfig $config, ReactiveMapGenerator $map): int
    {
        $target = resource_path('js/types/generated.d.ts');
        $scratch = $config->outputDirectory.DIRECTORY_SEPARATOR.'generated.d.ts';

        $files->ensureDirectoryExists($config->outputDirectory);
        $files->delete($scratch);

        TypeScriptTransformer::create($config)->execute();

        $types = $files->exists($scratch) ? $this->indent(trim($files->get($scratch))) : '';

        // A script file, not a module: `export {}` would scope the namespaces
        // to the file and nothing in the app could see `App.*`.
        $output = "// Generated by `php artisan types:generate`. Do not edit.\n\n"
            .$types."\n\n"
            .$map->generate()."\n"
            ."interface Window {\n  __APP_CONFIG__?: App.Support.RuntimeConfigPayload\n}\n";

        if ($this->option('check')) {
            $current = $files->exists($target) ? $files->get($target) : null;

            if ($current !== $output) {
                $this->components->error('resources/js/types/generated.d.ts is out of date. Run `php artisan types:generate` and commit the result.');

                return self::FAILURE;
            }

            $this->components->info('Generated types are up to date.');

            return self::SUCCESS;
        }

        $files->ensureDirectoryExists(dirname($target));
        $files->put($target, $output);
        $this->components->info('Wrote resources/js/types/generated.d.ts.');

        return self::SUCCESS;
    }

    /**
     * The writer emits one brace per line without indentation; nest by
     * brace depth so the file reads like the rest of the codebase.
     */
    private function indent(string $source): string
    {
        $depth = 0;
        $lines = [];

        foreach (explode("\n", $source) as $line) {
            $line = trim($line);

            if (str_starts_with($line, '}')) {
                $depth = max(0, $depth - 1);
            }

            $lines[] = $line === '' ? '' : str_repeat('  ', $depth).$line;

            if (str_ends_with($line, '{')) {
                $depth++;
            }
        }

        return implode("\n", $lines);
    }
}
