// Generated by `php artisan types:generate`. Do not edit.

declare namespace App {
  namespace Ai {
    namespace Data {
      export type AskAssistantArgs = {
        question: string,
      };
    }
  }
  namespace Data {
    export type InviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      status: string,
      createdAt: string,
    };
    export type MeData = {
      user: App.Data.UserData,
      abilities: string[],
      impersonating: boolean,
    };
    export type PersonData = {
      kind: string,
      id: string,
      name: string | null,
      email: string,
      role: string | null,
      avatarUrl: string | null,
      state: string,
      isRoot: boolean,
      emailVerified: boolean,
      twoFactorEnabled: boolean,
      lastLoginAt: string | null,
      invitedBy: string | null,
      expiresAt: string | null,
      createdAt: string,
      canAssignRole: boolean,
      canRemove: boolean,
      canResend: boolean,
    };
    export type PublicInviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      accountExists: boolean,
    };
    export type RoleData = {
      key: string,
      name: string,
      level: number,
      abilities: string[],
    };
    export type SavedViewData = {
      id: string,
      scope: string,
      name: string,
      params: Record<string, string>,
      isDefault: boolean,
      createdAt: string,
    };
    export type SecurityEventData = {
      id: string,
      event: string,
      ipAddress: string | null,
      device: string,
      context: Record<string, any> | null,
      createdAt: string,
    };
    export type SessionData = {
      id: string,
      device: string,
      ipAddress: string | null,
      lastActiveAt: string,
      createdAt: string,
      current: boolean,
    };
    export type SocialLinkData = {
      provider: string,
      label: string,
      icon: string,
      nickname: string | null,
      email: string | null,
      lastUsedAt: string | null,
      connectedAt: string,
    };
    export type UserData = {
      id: string,
      name: string,
      email: string,
      locale: string,
      avatarUrl: string | null,
      role: string | null,
      isRoot: boolean,
      emailVerified: boolean,
      twoFactorEnabled: boolean,
      lastLoginAt: string | null,
      createdAt: string,
      pendingEmail: string | null,
    };
  }
  namespace Services {
    namespace Ai {
      namespace Dto {
        export type StreamEventType = 'status' | 'delta' | 'done' | 'error';
      }
    }
  }
  namespace Support {
    export type AnalyticsPayload = {
      key: string,
      host: string,
    };
    export type EchoConfigPayload = {
      key: string,
      wsHost: string,
      wsPort: number,
      wssPort: number,
      forceTLS: boolean,
    };
    export type RuntimeConfigPayload = {
      version: string,
      apiBaseUrl: string,
      locale: string,
      features: {
        realtime: boolean,
        registration: boolean,
        impersonation: boolean,
        ai: boolean,
        push: boolean,
        social: boolean,
      },
      echo: App.Support.EchoConfigPayload | null,
      analytics: App.Support.AnalyticsPayload | null,
      socialProviders: App.Support.SocialProviderPayload[],
      vapidPublicKey: string | null,
    };
    export type SocialProviderPayload = {
      key: string,
      label: string,
      icon: string,
    };
    namespace Export {
      export type ExportFormat = 'csv' | 'xlsx' | 'pdf';
    }
  }
}
declare namespace Illuminate {
  export type CursorPaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      path: string,
      per_page: number,
      next_cursor: string | null,
      next_page_url: string | null,
      prev_cursor: string | null,
      prev_page_url: string | null,
    },
  };
  export type CursorPaginatorInterface<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
  export type LengthAwarePaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      total: number,
      current_page: number,
      first_page_url: string,
      from: number | null,
      last_page: number,
      last_page_url: string,
      next_page_url: string | null,
      path: string,
      per_page: number,
      prev_page_url: string | null,
      to: number | null,
    },
  };
  export type LengthAwarePaginatorInterface<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
}
declare namespace Spatie {
  namespace LaravelData {
    export type CursorPaginatedDataCollection<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
    export type PaginatedDataCollection<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
  }
}

declare namespace Kit {
  export type ReactiveMap = {}
}

declare namespace Kit {
  export type AiMap = {
    'assistant.ask': {
      args: App.Ai.Data.AskAssistantArgs
    }
  }
}

interface Window {
  __APP_CONFIG__?: App.Support.RuntimeConfigPayload
}
