// Generated by `php artisan types:generate`. Do not edit.

declare namespace App {
  namespace Data {
    export type InviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      status: string,
      createdAt: string,
    };
    export type MeData = {
      user: App.Data.UserData,
      abilities: string[],
      impersonating: boolean,
    };
    export type PublicInviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      accountExists: boolean,
    };
    export type RoleData = {
      key: string,
      name: string,
      level: number,
      abilities: string[],
    };
    export type UserData = {
      id: string,
      name: string,
      email: string,
      locale: string,
      role: string | null,
      isRoot: boolean,
      emailVerified: boolean,
      twoFactorEnabled: boolean,
      lastLoginAt: string | null,
      createdAt: string,
    };
  }
  namespace Support {
    export type AnalyticsPayload = {
      key: string,
      host: string,
    };
    export type EchoConfigPayload = {
      key: string,
      wsHost: string,
      wsPort: number,
      wssPort: number,
      forceTLS: boolean,
    };
    export type RuntimeConfigPayload = {
      version: string,
      apiBaseUrl: string,
      locale: string,
      features: {
        realtime: boolean,
        registration: boolean,
        impersonation: boolean,
      },
      echo: App.Support.EchoConfigPayload | null,
      analytics: App.Support.AnalyticsPayload | null,
    };
  }
}
declare namespace Illuminate {
  export type CursorPaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      path: string,
      per_page: number,
      next_cursor: string | null,
      next_page_url: string | null,
      prev_cursor: string | null,
      prev_page_url: string | null,
    },
  };
  export type CursorPaginatorInterface<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
  export type LengthAwarePaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      total: number,
      current_page: number,
      first_page_url: string,
      from: number | null,
      last_page: number,
      last_page_url: string,
      next_page_url: string | null,
      path: string,
      per_page: number,
      prev_page_url: string | null,
      to: number | null,
    },
  };
  export type LengthAwarePaginatorInterface<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
}
declare namespace Spatie {
  namespace LaravelData {
    export type CursorPaginatedDataCollection<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
    export type PaginatedDataCollection<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
  }
}

declare namespace Kit {
  export type ReactiveMap = {}
}

interface Window {
  __APP_CONFIG__?: App.Support.RuntimeConfigPayload
}
