// Generated by `php artisan types:generate`. Do not edit.

declare namespace App {
  namespace Ai {
    namespace Data {
      export type AskAssistantArgs = {
        question: string,
      };
    }
  }
  namespace Data {
    export type AccessTokenData = {
      id: string,
      name: string,
      abilities: string[],
      lastUsedAt: string | null,
      expiresAt: string | null,
      createdAt: string,
    };
    export type AttachmentData = {
      id: string,
      name: string,
      mimeType: string,
      size: number,
      width: number | null,
      height: number | null,
      url: string,
      thumbnailUrl: string | null,
      uploadedBy: string | null,
      createdAt: string,
    };
    export type AuditChangeData = {
      field: string,
      before: string | null,
      after: string | null,
      redacted: boolean,
    };
    export type AuditEntryData = {
      id: string,
      event: string,
      actorName: string | null,
      actorAvatarUrl: string | null,
      impersonatorName: string | null,
      changes: App.Data.AuditChangeData[],
      createdAt: string,
    };
    export type InviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      status: string,
      createdAt: string,
    };
    export type ListNotificationsArgs = {
      userId: string,
      status: App.Enums.NotificationStatus | null,
    };
    export type ListPeopleArgs = {
      viewerId: string,
      params: Record<string, string | number> | null,
    };
    export type MeData = {
      user: App.Data.UserData,
      abilities: string[],
      impersonating: boolean,
    };
    export type NotificationChannelData = {
      key: string,
      available: boolean,
      deliverable: boolean,
    };
    export type NotificationData = {
      id: string,
      type: string,
      data: Record<string, any>,
      status: App.Enums.NotificationStatus,
      deliveries: Record<string, string>,
      seenAt: string | null,
      archivedAt: string | null,
      createdAt: string,
    };
    export type NotificationScopeArgs = {
      userId: string,
      ids: string[] | null,
    };
    export type NotificationSettingsData = {
      channels: App.Data.NotificationChannelData[],
      types: App.Data.NotificationTypeData[],
      phone: App.Data.PhoneData,
      escalationMinutes: number,
    };
    export type NotificationSummaryArgs = {
      userId: string,
    };
    export type NotificationSummaryData = {
      unseen: number,
      total: number,
    };
    export type NotificationTypeData = {
      key: string,
      group: string,
      channels: string[],
      required: string[],
      enabled: string[],
    };
    export type PeoplePageData = {
      data: App.Data.PersonData[],
      current_page: number,
      last_page: number,
      per_page: number,
      total: number,
      from: number | null,
      to: number | null,
      counts: {
        active: number,
        pending: number,
        total: number,
      },
    };
    export type PersonData = {
      kind: string,
      id: string,
      name: string | null,
      email: string,
      role: string | null,
      avatarUrl: string | null,
      state: string,
      isRoot: boolean,
      emailVerified: boolean,
      twoFactorEnabled: boolean,
      lastLoginAt: string | null,
      invitedBy: string | null,
      expiresAt: string | null,
      createdAt: string,
      canAssignRole: boolean,
      canRemove: boolean,
      canResend: boolean,
    };
    export type PhoneData = {
      phone: string | null,
      verified: boolean,
      pendingPhone: string | null,
      resendIn: number,
    };
    export type PresenceMemberData = {
      id: string,
      name: string,
      avatarUrl: string | null,
      color: string,
    };
    export type PublicInviteData = {
      id: string,
      email: string,
      role: string,
      invitedBy: string | null,
      expiresAt: string,
      accountExists: boolean,
    };
    export type RecordArgs = {
      type: string,
      id: string,
    };
    export type RoleData = {
      key: string,
      name: string,
      level: number,
      abilities: string[],
    };
    export type SaveWebhookArgs = {
      url: string,
      events: string[],
      description: string | null,
      active: boolean,
      id: string | null,
    };
    export type SavedViewData = {
      id: string,
      scope: string,
      name: string,
      params: Record<string, string>,
      isDefault: boolean,
      createdAt: string,
    };
    export type SecurityEventData = {
      id: string,
      event: string,
      ipAddress: string | null,
      device: string,
      context: Record<string, any> | null,
      createdAt: string,
    };
    export type SessionData = {
      id: string,
      device: string,
      ipAddress: string | null,
      lastActiveAt: string,
      createdAt: string,
      current: boolean,
    };
    export type SocialLinkData = {
      provider: string,
      label: string,
      icon: string,
      nickname: string | null,
      email: string | null,
      lastUsedAt: string | null,
      connectedAt: string,
    };
    export type UserData = {
      id: string,
      name: string,
      email: string,
      locale: string,
      avatarUrl: string | null,
      role: string | null,
      isRoot: boolean,
      emailVerified: boolean,
      twoFactorEnabled: boolean,
      lastLoginAt: string | null,
      createdAt: string,
      pendingEmail: string | null,
    };
    export type WebhookArgs = {
      id: string,
    };
    export type WebhookDeliveryData = {
      id: string,
      event: string,
      status: string,
      attempts: number,
      responseStatus: number | null,
      responseBody: string | null,
      payload: string,
      deliveredAt: string | null,
      createdAt: string,
    };
    export type WebhookEndpointData = {
      id: string,
      url: string,
      description: string | null,
      events: string[],
      active: boolean,
      lastStatus: string | null,
      lastEventAt: string | null,
      createdAt: string,
    };
    export type WebhookEventsData = {
      events: string[],
    };
    export type WebhookSecretData = {
      endpoint: App.Data.WebhookEndpointData,
      secret: string,
    };
  }
  namespace Enums {
    export type NotificationChannel = 'push' | 'mail' | 'sms';
    export type NotificationStatus = 'unseen' | 'seen' | 'archived';
  }
  namespace Services {
    namespace Ai {
      namespace Dto {
        export type StreamEventType = 'status' | 'delta' | 'done' | 'error';
      }
    }
  }
  namespace Support {
    export type AnalyticsPayload = {
      key: string,
      host: string,
    };
    export type EchoConfigPayload = {
      key: string,
      wsHost: string,
      wsPort: number,
      wssPort: number,
      forceTLS: boolean,
    };
    export type RuntimeConfigPayload = {
      version: string,
      apiBaseUrl: string,
      locale: string,
      features: {
        realtime: boolean,
        registration: boolean,
        impersonation: boolean,
        ai: boolean,
        push: boolean,
        sms: boolean,
        social: boolean,
      },
      echo: App.Support.EchoConfigPayload | null,
      analytics: App.Support.AnalyticsPayload | null,
      socialProviders: App.Support.SocialProviderPayload[],
      vapidPublicKey: string | null,
    };
    export type SocialProviderPayload = {
      key: string,
      label: string,
      icon: string,
    };
    namespace Export {
      export type ExportFormat = 'csv' | 'xlsx' | 'pdf';
    }
  }
}
declare namespace Illuminate {
  export type CursorPaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      path: string,
      per_page: number,
      next_cursor: string | null,
      next_page_url: string | null,
      prev_cursor: string | null,
      prev_page_url: string | null,
    },
  };
  export type CursorPaginatorInterface<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
  export type LengthAwarePaginator<TKey, TValue> = {
    data: TKey extends string ? Record<TKey, TValue> : TValue[],
    links: {
      url: string | null,
      label: string,
      active: boolean,
    }[],
    meta: {
      total: number,
      current_page: number,
      first_page_url: string,
      from: number | null,
      last_page: number,
      last_page_url: string,
      next_page_url: string | null,
      path: string,
      per_page: number,
      prev_page_url: string | null,
      to: number | null,
    },
  };
  export type LengthAwarePaginatorInterface<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
}
declare namespace Spatie {
  namespace LaravelData {
    export type CursorPaginatedDataCollection<TKey, TValue> = Illuminate.CursorPaginator<TKey, TValue>;
    export type PaginatedDataCollection<TKey, TValue> = Illuminate.LengthAwarePaginator<TKey, TValue>;
  }
}

declare namespace Kit {
  export type ReactiveMap = {
    'attachments.list': {
      args: App.Data.RecordArgs
      result: Array<App.Data.AttachmentData>
    }
    'audit.history': {
      args: App.Data.RecordArgs
      result: Array<App.Data.AuditEntryData>
    }
    'notifications.archive': {
      args: App.Data.NotificationScopeArgs
      result: App.Data.NotificationSummaryData
    }
    'notifications.list': {
      args: App.Data.ListNotificationsArgs
      result: Array<App.Data.NotificationData>
    }
    'notifications.markSeen': {
      args: App.Data.NotificationScopeArgs
      result: App.Data.NotificationSummaryData
    }
    'notifications.restore': {
      args: App.Data.NotificationScopeArgs
      result: App.Data.NotificationSummaryData
    }
    'notifications.summary': {
      args: App.Data.NotificationSummaryArgs
      result: App.Data.NotificationSummaryData
    }
    'people.list': {
      args: App.Data.ListPeopleArgs
      result: App.Data.PeoplePageData
    }
    'webhooks.create': {
      args: App.Data.SaveWebhookArgs
      result: App.Data.WebhookSecretData
    }
    'webhooks.delete': {
      args: App.Data.WebhookArgs
      result: unknown
    }
    'webhooks.deliveries': {
      args: App.Data.WebhookArgs
      result: Array<App.Data.WebhookDeliveryData>
    }
    'webhooks.events': {
      args: Record<string, never>
      result: App.Data.WebhookEventsData
    }
    'webhooks.list': {
      args: Record<string, never>
      result: Array<App.Data.WebhookEndpointData>
    }
    'webhooks.rotateSecret': {
      args: App.Data.WebhookArgs
      result: App.Data.WebhookSecretData
    }
    'webhooks.test': {
      args: App.Data.WebhookArgs
      result: App.Data.WebhookDeliveryData
    }
    'webhooks.update': {
      args: App.Data.SaveWebhookArgs
      result: App.Data.WebhookEndpointData
    }
  }
}

declare namespace Kit {
  export type AiMap = {
    'assistant.ask': {
      args: App.Ai.Data.AskAssistantArgs
    }
  }
}

interface Window {
  __APP_CONFIG__?: App.Support.RuntimeConfigPayload
}
