<?php

declare(strict_types=1);

namespace Kit\Reactive\Console;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Kit\Reactive\Registry\Catalog;

/**
 * Writes the query and mutation name maps to bootstrap/cache/reactive.php so
 * a boot outside Octane does not walk the feature directories. Wired into
 * `optimize` through the service provider.
 */
class CacheCommand extends Command
{
    protected $signature = 'reactive:cache';

    protected $description = 'Cache the reactive query and mutation name maps';

    public function handle(Catalog $catalog, Filesystem $files): int
    {
        $path = (string) config('reactive.cache_path');
        $maps = $catalog->scan();

        $files->ensureDirectoryExists(dirname($path));
        $files->put($path, "<?php\n\n// Generated by `php artisan reactive:cache`. Do not edit.\n\nreturn ".var_export($maps, true).";\n");

        $this->components->info(sprintf(
            'Cached %d quer(ies) and %d mutation(s).',
            count($maps['queries']),
            count($maps['mutations']),
        ));

        return self::SUCCESS;
    }
}
