import { createHttpTransport, createReactive } from '@kit/reactive-vue'
import { toast } from 'vue-sonner'

import { api } from '~/api'
import { toastError } from '~/lib/toast-error'
import { createEcho } from '~/plugins/echo'
import { useI18n } from '~/plugins/i18n'

export const echo = createEcho()

const { t, te } = useI18n()

/**
 * The app's typed reactive layer. `Kit.ReactiveMap` is generated by
 * types:generate from every #[ReactiveQuery] / #[ReactiveMutation], so a
 * name that does not exist on the server is a type error here.
 *
 * Toasts read `mutations.<name>.success` (only when the key exists) and
 * `mutations.<name>.error` (always, so a missing key surfaces in tests
 * rather than echoing the key back).
 */
export const reactive = createReactive<Kit.ReactiveMap>({
  transport: createHttpTransport(api.client),
  echo,
  onMutationSuccess: (name) => {
    if (te(`mutations.${name}.success`)) toast.success(t(`mutations.${name}.success`))
  },
  onMutationError: (name, error) => toastError(t, `mutations.${name}.error`, error),
})

export const { useReactiveQuery, useReactiveMutation } = reactive
